trigger:
  branches:
    include:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

variables:
- name: MAVEN_CACHE_FOLDER
  value: $(Pipeline.Workspace)/.m2/repository
- name: MAVEN_OPTS
  value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)  -s $(muleSettingsFile.secureFilePath) -Dkey=mymulesoft '
- name: MAVEN_BUILD
  value: '-Dkey=mymulesoft -DskipTests'
- name: MAVEN_OPTS_TEST_CUCUMBER
  value: '-Dtestfile=src/test/javarunner.TestRunner.java -DskipTests'    

steps:
- task: DownloadSecureFile@1
  name: muleSettingsFile
  displayName: 'Download Mulesoft Settings'
  inputs:
    secureFile: 'settings.xml'
- task: CacheBeta@0
  inputs:
    key: $(Build.SourcesDirectory)/pom.xml
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'package $(MAVEN_OPTS) $(MAVEN_BUILD)'
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'pom'
  displayName: Maven Build
- task: CopyFiles@2
  inputs:
    Contents: '**/target/*.jar'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
    flattenFolders: true      
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     goals: 'test $(MAVEN_OPTS)'
#     sqMavenPluginVersionChoice: 'pom'
#   displayName: Munit Test
# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: '**/TEST-*.xml' 
#     #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
#     mergeTestResults: true # Optional
#     #failTaskOnFailedTests: false # Optional
#     # testRunTitle: APIOPS-MUNIT
#     #buildPlatform: # Optional
#     #buildConfiguration: # Optional
#     publishRunAttachments: true # Optional 
#   displayName: MUNIT Test Publish
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'test $(MAVEN_OPTS) $(MAVEN_OPTS_TEST_CUCUMBER)'
    sqMavenPluginVersionChoice: 'pom'
  displayName: Functional Test 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)
    artifact: 'drop'
- task: PublishCucumberReport@1
  inputs:
    jsonDir: '$(System.DefaultWorkingDirectory)/drop/target/'
    outputPath: '$(System.DefaultWorkingDirectory)'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true